# Generated by Django 3.2.10 on 2022-08-02 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waveapp', '0002_alter_wave_amplitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wave',
        ),
    ]
