# Generated by Django 3.2.10 on 2022-08-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveapp', '0006_wave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='song/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
