# Generated by Django 3.2.10 on 2022-08-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveapp', '0008_auto_20220805_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='waveform',
            field=models.ImageField(null=True, upload_to='waveforms'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='songs'),
        ),
    ]
