# Generated by Django 3.2.10 on 2022-08-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveapp', '0009_auto_20220809_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.FileField(upload_to='songs')),
                ('waveform', models.ImageField(null=True, upload_to='waveforms')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
